deploy_staging:
    stage: deploy
    script:
        - echo "Deploy to staging server"
        - apt-get update -qq && apt-get install -y -qq lftp
        - lftp -c "set ftp:ssl-allow no; open -u $USER_DEV,'$PASS_DEV' $HOST_DEV; mirror -Rv ./ ./ --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/ --exclude user_guide/ --exclude assets/plugins/ --exclude assets/fonts/"
    environment:
        name: staging
    only:
        - main
deploy_production:
    stage: deploy
    script:
        - echo "Deploy to production server"
        - apt-get update -qq && apt-get install -y -qq lftp
        - lftp -c "set ftp:ssl-allow no; open -u $USER_PROD,'$PASS_PROD' $HOST_PROD; mirror -Rv ./ ./ --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/ --exclude user_guide/ --exclude assets/plugins/ --exclude assets/fonts/"
    environment:
        name: production
    when: manual
    only:
        - main